version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    working_dir: /var/www/html/src
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      APP_ENV: local
      DB_HOST: db
      DB_DATABASE: laravel_db
      DB_USERNAME: laravel_user
      DB_PASSWORD: laravel_password
      CHOKIDAR_USEPOLLING: "true"          # Vite/HMR の監視安定化
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5173:5173"                        # Vite dev server（開発時のみ使用）
    networks:
      - laravel_network
    restart: unless-stopped

  # Web (Nginx)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - laravel_network
    restart: unless-stopped

  # DB (MySQL)
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-proot_password"]
      interval: 5s
      timeout: 3s
      retries: 30
    restart: unless-stopped
    # ※ ports: を定義しない＝ホストからは直接アクセス不可

volumes:
  mysql_data:

networks:
  laravel_network:
    driver: bridge
